// src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'my-app';
  captchaHandler=(captchaObj: any)=> {
    (window as any).captchaObj = captchaObj;
    captchaObj
      .appendTo("#captcha")
      .onReady(function () {
        console.log("ready");
      })
      .onNextReady(function () {
        console.log("nextReady");
      })
      .onBoxShow(function () {
        console.log("boxShow");
      })
      .onError(function (e: any) {
        console.log(e);
      })
      .onSuccess(  () => {
        if (this.captchaConfig.config.product === "bind") {
          this.validate();
        }
      });
  }
  captchaConfig = {
    config: {
      captchaId: "54088bb07d2df3c46b79f80300b0abbe",
      language: "en",
      product: "bind",
    },
    handler: this.captchaHandler,
  };
  constructor( private httpClient: HttpClient){}
  validate() {
    var result = (window as any).captchaObj.getValidate();
    if (!result) {
      alert("请先完成验证！");
      return;
    }
    const params = Object.assign(result, {
      captcha_id: "54088bb07d2df3c46b79f80300b0abbe",
    });
    this.httpClient.get("/demo/login", params)
      .subscribe((res: any) => {
        if (res.data.result) {
          console.log(res.data);
          alert(res.data.result);
        }
      });
  }
  login() {
    if (this.captchaConfig.config.product === "bind") {
      if ((window as any).captchaObj) {
        (window as any).captchaObj.showCaptcha();
      } else {
        alert("请等待验证初始化完成");
        // return false;
      }
    } else {
      this.validate();
    }
  }
}


<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<style>
  :host {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
    font-size: 14px;
    color: #333;
    box-sizing: border-box;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  /* Responsive Styles */
  @media screen and (max-width: 767px) {
    .card-container > *:not(.circle-link) ,
    .terminal {
      width: 100%;
    }

    .card:not(.highlight-card) {
      height: 16px;
      margin: 8px 0;
    }

    .card.highlight-card span {
      margin-left: 72px;
    }

    svg#rocket-smoke {
      right: 120px;
      transform: rotate(-5deg);
    }
  }

  @media screen and (max-width: 575px) {
    svg#rocket-smoke {
      display: none;
      visibility: hidden;
    }
  }
</style>


<div class="content demoform" role="main">
  <form id="form">
    <div
      class="inp"
      [class]="captchaConfig.config.product === 'bind' ? 'minWidth' : ''"
    >
      <div class="user">user</div>
      <input
        type="email"
        id="email"
        autocomplete="false"
        placeholder="hello@geetest.com"
      />
    </div>
    <div class="inp">
      <div class="pass"></div>
      <input
        type="password"
        id="pass"
        autocomplete="false"
        placeholder="******"
      />
    </div>
    <div
      id="captcha"
      [class]="captchaConfig.config.product === 'bind' ? 'hideHeight' : ''"
    >
      <app-geetest-captcha [captchaConfig]="captchaConfig" ></app-geetest-captcha>
    </div>
    <div class="login" (click)="login()">
      {{ captchaConfig.config.language === "en" ? "login" : "登录" }}
    </div>
  </form>
</div>

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<router-outlet></router-outlet>

// src/App.vue
<!--
 * @Description: 
 * @Version: 1.0.0
 * @Date: 2022-04-11 11:22:53
 * @LastEditors: Yawen Yang
 * @LastEditTime: 2023-01-09 14:30:42
-->
<template>
  <div class="demoform">
    <form id="form">
      <div
        class="inp"
        :class="captchaConfig.config.product === 'bind' ? 'minWidth' : ''"
      >
        <div class="user">user</div>
        <input
          type="email"
          id="email"
          autocomplete="false"
          placeholder="hello@geetest.com"
        />
      </div>
      <div class="inp">
        <div class="pass"></div>
        <input
          type="password"
          id="pass"
          autocomplete="false"
          placeholder="******"
        />
      </div>
      <div
        id="captcha"
        :class="captchaConfig.config.product === 'bind' ? 'hideHeight' : ''"
      >
        <GeetestCaptcha :captcha-config="captchaConfig" />
      </div>
      <div class="login" @click="login">
        {{ captchaConfig.config.language === "en" ? "login" : "登录" }}
      </div>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, toRefs, getCurrentInstance } from "vue";
import GeetestCaptcha from "./components/GeetestCaptcha.vue";

declare global {
  interface Window {
    [propName: string]: never;
  }
}
export default defineComponent({
  name: "App",
  components: {
    GeetestCaptcha,
  },
  setup() {
    const instance: any = getCurrentInstance();
    let data = reactive({
      captchaConfig: {
        config: {
          captchaId: "54088bb07d2df3c46b79f80300b0abbe",
          language: "en",
          product: "bind",
        },
        handler: captchaHandler,
      },
    });
    function login() {
      if (data.captchaConfig.config.product === "bind") {
        if (window.captchaObj) {
          (window as any).captchaObj.showCaptcha();
        } else {
          alert("请等待验证初始化完成");
          return false;
        }
      } else {
        validate();
      }
    }

    function validate() {
      var result = (window as any).captchaObj.getValidate();
      if (!result) {
        alert("请先完成验证！");
        return;
      }
      instance.proxy
        .$axios({
          method: "get",
          url: "/demo/login",
          params: Object.assign(result, {
            captcha_id: "54088bb07d2df3c46b79f80300b0abbe",
          }),
        })
        .then((res: any) => {
          if (res.data.result) {
            console.log(res.data);
            alert(res.data.result);
          }
        });
    }

    function captchaHandler(captchaObj: any) {
      (window as any).captchaObj = captchaObj;
      captchaObj
        .appendTo("#captcha")
        .onReady(function () {
          console.log("ready");
        })
        .onNextReady(function () {
          console.log("nextReady");
        })
        .onBoxShow(function () {
          console.log("boxShow");
        })
        .onError(function (e: any) {
          console.log(e);
        })
        .onSuccess(function () {
          if (data.captchaConfig.config.product === "bind") {
            validate();
          }
        });
    }

    return {
      login,
      ...toRefs(data),
    };
  },
});
</script>

<style lang="scss" scope>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
.demoform {
  margin: 100px auto 0;
  width: 340px;
  height: 600px;
  position: relative;
  form {
    box-sizing: content-box;

    .inp {
      background: #ffffff;
      border: 1px solid #d1d6e0;
      box-sizing: border-box;
      border-radius: 4px;
      margin: 20px 0px;
      font-size: 0;
      position: relative;
      text-align: left;

      .user {
        margin: 15px 0 15px 13px;
        background-image: url("./assets/user.png");
        background-size: 100%;
        width: 20px;
        height: 20px;
        display: inline-block;
      }
      .pass {
        margin: 15px 13px;
        background-image: url("./assets/lock.png");
        background-size: 100%;
        width: 20px;
        height: 20px;
        display: inline-block;
      }
      > input {
        width: 213px;
        font-size: 14px;
        position: absolute;
        top: 7px;
        left: 45px;
        height: 36px;
        border: none;
        border-left: 1px solid #d1d6e0;
        background-color: #bab1bb00 !important;
        outline: transparent;
        text-indent: 5px;
      }
      input:-internal-autofill-selected {
        background-color: red !important;
        -webkit-transition: background-color 5000s ease-in-out 0s !important;
        transition: background-color 5000s ease-in-out 0s !important;
      }
    }

    #captcha {
      height: 50px;

      &.hideHeight {
        height: 0;
      }
    }

    .login {
      background: #347eff;
      border-radius: 4px;
      margin: 20px 0px;
      width: 100%;
      height: 50px;
      color: white;
      text-align: center;
      line-height: 50px;
      cursor: pointer;
    }
  }
}
</style>
